- type: replace
  path: /releases?/name=bpm?
  value:
    name: "bpm"
    url: "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.4.9"
    version: "1.4.9"
    sha1: "e4d3a64d299a319f31b4d012fea2585134866bc8"
