- type: replace
  path: /releases?/name=postgres?
  value:
    name: postgres
    version: "54.0.0"
    url: "https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=54.0.0"
    sha1: "dbbe92802e79900010bc2cc019833108519a110e"
