- type: replace
  path: /releases?/name=prometheus?
  value:
    name: prometheus
    version: 26.4.0
    url: https://bosh.io/d/github.com/cloudfoundry-community/prometheus-boshrelease?v=26.4.0
    sha1: 973ff5d23d10627b822520c728c10775d10e760d
