- type: replace
  path: /releases?/name=prometheus?
  value:
    name: prometheus
    version: 27.1.0
    url: https://bosh.io/d/github.com/cloudfoundry-community/prometheus-boshrelease?v=27.1.0
    sha1: 2fc175187a4d1ea0e6e28f91020535260c45626d
