- type: replace
  path: /releases?/name=prometheus?
  value:
    name: prometheus
    version: 27.2.1
    url: https://bosh.io/d/github.com/cloudfoundry-community/prometheus-boshrelease?v=27.2.1
    sha1: 93fe65a53d26a18b78e0b373e2849c1b1528b90a
