- type: replace
  path: /releases?/name=prometheus?
  value:
    name: prometheus
    version: 27.2.0
    url: https://bosh.io/d/github.com/cloudfoundry-community/prometheus-boshrelease?v=27.2.0
    sha1: 5ac2c9e1b94ef635f1bd467b7fd63a67e01baf22
