#!/bin/bash
set -eu
KIT=prometheus

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

cleanup() {
	for deployment in "$@"; do
		echo "> deleting ${deployment}"
		$BOSH -n -d "${deployment}" delete-deployment

		for disk in $($BOSH disks --orphaned | grep "${deployment}" | awk '{print $1}'); do
			echo "  - removing disk $disk"
			$BOSH -n delete-disk "$disk"
		done
	done
}

header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
$BOSH deployments

header "Cleaning up from any previous deployments (if necessary)..."
cleanup ci-baseline-${KIT}
safe rm -rf secret/ci/baseline/${KIT}

header "Deploying BASELINE environment to verify functionality..."
cd dev
# make sure hooks are executable before screaming at shipit for failing.
genesis compile-kit --name $KIT -v 9.9.9 --force
cd ..
genesis add-secrets ci-baseline
genesis deploy -y ci-baseline
$BOSH -d ci-baseline-${KIT} instances --ps

header "Validating BASELINE environment..."
password=$(safe get secret/ci/baseline/prometheus/admin:password)
response=$(curl -k https://admin:$password@10.128.8.132:8080/-/healthy)
if [[ $response != "Prometheus is Healthy." ]]; then
	echo "https://<prometheus-ip>:8080/-/healthy:"
	echo "expected 'Prometheus is Healthy.'"
	echo "     got '$response'"
	exit 1
fi
cleanup ci-baseline-${KIT}
