---
exodus:
  monitor-cf: true

meta:
  base_cf_env:             (( grab params.cf_env || genesis.env || params.env ))
  default_cf_exodus_path:  (( concat meta.base_cf_env "/cf" ))
  cf_exodus_path:          (( grab params.cf_exodus_path || meta.default_cf_exodus_path ))
  cf_exodus_src:           (( concat  $GENESIS_EXODUS_MOUNT meta.cf_exodus_path ":" ))

  cf_system_domain:        (( vault meta.cf_exodus_src "system_domain" ))
  cf_firehose_uaa_vault:   (( vault meta.cf_exodus_src "vaulted_uaa_clients" ))
  uaa_client_id:           firehose
  uaa_client_secret:       (( vault meta.cf_firehose_uaa_vault ))
  default_rlp_gateway_url: (( concat "https://log-stream." meta.cf_system_domain ))

instance_groups:
- name: prometheus
  jobs:
  - name: cf_exporter
    release: prometheus
    properties:
      cf_exporter:
        cf:
          api_url:         (( vault meta.cf_exodus_src "api_url" ))
          client_id:       (( grab meta.uaa_client_id ))
          client_secret:   (( grab meta.uaa_client_secret ))
          deployment_name: (( concat meta.base_cf_env "-cf" ))
        metrics:
          environment:     (( grab meta.environment ))
        skip_ssl_verify:   (( grab meta.skip_ssl_verify ))

  - name: firehose_exporter
    release: prometheus
    properties:
      firehose_exporter:
        logging:
          url: (( grab params.rlp_gateway_url || meta.default_rlp_gateway_url ))
          use_legacy_firehose: false
        doppler:
          subscription_id: (( grab meta.environment ))
          max_retry_count: 300
        uaa:
          url:             (( concat "https://uaa." meta.cf_system_domain ))
          client_id:       (( grab meta.uaa_client_id ))
          client_secret:   (( grab meta.uaa_client_secret ))
        metrics:
          environment:     (( grab meta.environment ))
        skip_ssl_verify:   (( grab meta.skip_ssl_verify ))


  - name: cloudfoundry_dashboards
    release: prometheus
  - name: cloudfoundry_alerts
    release: prometheus

  - name: grafana
    properties:
      grafana:
        prometheus:
          dashboard_folders:
          - name: Cloudfoundry
            files:
            - /var/vcap/jobs/cloudfoundry_dashboards/cf*.json
          - name: Prometheus
            files:
            - /var/vcap/jobs/cloudfoundry_dashboards/prometheus*.json


  - name: prometheus2
    properties:
      prometheus:
        rule_files:
        - /var/vcap/jobs/cloudfoundry_alerts/*.alerts.yml
