#!/bin/bash
set -eu
vault="secret/$GENESIS_VAULT_PREFIX"
target=$GENESIS_ENVIRONMENT


list() {
  echo "The following addons are defined:"
  echo
  echo "  list                List out all supported addons."
  echo "  visit-prometheus    [shortcut: vp] Visit the Prometheus Web UI (macOS & Linux only)"
  echo "  visit-grafana       [shortcut: vg] Visit the Grafana dashboard (macOS & Linux only)"
  echo "  visit-alertmanager  [shortcut: va] Visit the AlertManager dashboard (macOS & Linux only)"
  echo "  runtime-config      [shortcut: rc] Generate a runtime configuration for node-exporter"
  echo
}

ostype() {
  UNAME=$(uname)

  if [ "$UNAME" == "Linux" ] ; then
    export cmd="xdg-open"
  elif [ "$UNAME" == "Darwin" ] ; then
    export cmd="open"
  fi
}

case $GENESIS_ADDON_SCRIPT in
list)
  list
  exit 0
  ;;

visit-prometheus|vp)
  ostype
  if ! command -v ${cmd} >/dev/null 2>&1; then
    echo "The 'visit-prometheus' addon script only works on macOS and Linux, currently."
    exit 1
  fi
  url=$(exodus prometheus_url)
  password=$(safe get $vault/admin:password)
  ${cmd} "https://admin:$password@$url"
  ;;

visit-alertmanager|va)
  ostype
  if ! command -v ${cmd} >/dev/null 2>&1; then
    echo "The 'visit-alertmanager' addon script only works on macOS and Linux, currently."
    exit 1
  fi
  url=$(exodus alertmanager_url)
  password=$(safe get $vault/admin:password)
  ${cmd} "https://admin:$password@$url"
  ;;

visit-grafana|vg)
  ostype
  if ! command -v ${cmd} >/dev/null 2>&1; then
    echo "The 'visit-grafana' addon script only works on macOS and Linux, currently."
    exit 1
  fi
  url=$(exodus grafana_url)
  password=$(safe get $vault/admin:password)
  echo "Here's the credentials you'll need to sign in: "
  echo
  echo -e "  \033[1m\033[1;36m username: \033[0m admin"
  echo -e "  \033[1m\033[1;36m password: \033[0m $password"
  echo
  ${cmd} "https://$url"
  ;;

runtime-config|rc)
  cat <<EOF
releases:
  - name: node-exporter
    version: 5.5.0
    url:     https://github.com/bosh-prometheus/node-exporter-boshrelease/releases/download/v5.5.0/node-exporter-5.5.0.tgz
    sha1:    e013bead7ca3d0128a56dc71b1294fa0d75eea36

addons:
  - name: node_exporter
    jobs:
      - name: node_exporter
        release: node-exporter
    include:
      stemcell:
        - os: ubuntu-jammy
        - os: ubuntu-bionic
        - os: ubuntu-xenial
    properties: {}
EOF
  ;;

*)
  echo "Unrecognized Prometheus Genesis Kit addon."
  list
  exit 1
  ;;
esac
