#!/bin/bash
set -eu

vault="secret/$GENESIS_VAULT_PREFIX"

describe \
  "" \
  "#B{Prometheus Information}" \
  "" \
  "Prometheus endpoint information" \
  "  #C{https://$(exodus prometheus_url)}" \
  "" \
  "Grafana endpoint information" \
  "  #C{https://$(exodus grafana_url)}" \
  "" \
  "AlertManager endpoint information" \
  "  #C{https://$(exodus alertmanager_url)}" \
  "" \
  "HTTP auth credentials" \
  "  username: #M{admin}" \
  "  password: #G{$(safe get $vault/admin:password)}"