#!/bin/bash
set -eu

if [[ $GENESIS_DEPLOY_RC == 0 ]]
then
  describe \
    "" \
    "#M{$GENESIS_ENVIRONMENT} Prometheus deployed!" \
    "" \
    "For details about the deployment, run" \
    "" \
    "  #G{genesis info $GENESIS_ENVIRONMENT}" \
    "" \
    "To visit the Prometheus page:" \
    "" \
    "  #G{genesis do $GENESIS_ENVIRONMENT -- visit-prometheus}" \
    "" \
    "To visit the Grafana page:" \
    "" \
    "  #G{genesis do $GENESIS_ENVIRONMENT -- visit-grafana}" \
    "" \
    "To visit the AlertManager page:" \
    "" \
    "  #G{genesis do $GENESIS_ENVIRONMENT -- visit-alertmanager}" \
    "" \
    "To generate a node exporter runtime config:" \
    "" \
    "  #G{genesis do $GENESIS_ENVIRONMENT -- runtime-config}" \
    ""
fi
exit 0