#!/bin/bash
set -eu

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

cleanup() {
	for deployment in "$@"; do
		echo "> deleting ${deployment}"
		$BOSH -n -d "${deployment}" delete-deployment

		for disk in $($BOSH disks --orphaned | grep "${deployment}" | awk '{print $1}'); do
			echo "  - removing disk $disk"
			$BOSH -n delete-disk "$disk"
		done
	done
}

header "Validating BOSH_* environment variables..."
set | grep BOSH_ || true

header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
$BOSH deployments

header "Cleaning up from any previous deployments (if necessary)..."
cleanup ci-baseline-prometheus
safe rm -rf secret/genesis-ci/prometheus

header "Deploying BASELINE environment to verify functionality..."
cd dev
genesis compile-kit --name prometheus -v 9.9.9 --force # make sure hooks are executable before screaming at shipit for failing.
cd ..
genesis add-secrets ci-baseline 
cat ci-baseline.yml
pwd
ls
cat dev/kit.yml
genesis -v
genesis deploy -y ci-baseline
$BOSH -d ci-baseline-prometheus instances --ps
header "Validating BASELINE prometheus..."
bosh -d ci-baseline-prometheus vms
password=$(safe get secret/genesis-ci/prometheus/ci/baseline/admin:password)
response=$(curl -k https://admin:$password@10.200.190.135:8080/-/healthy)
if [[ $response == "Prometheus is Healthy." ]]; then
  cleanup ci-baseline-prometheus
  exit 0
fi
echo "Expected https://10.200.190.135:8080/-/healthy to return 'Prometheus is Healthy.' but instead" \
     "got $response"
cleanup ci-baseline-prometheus
exit 1


