jobs:
- name: postgres-release
  public: true
  serial: true
  serial_groups: [bosh-release]
  plan:
    - do:
      - in_parallel:
        - { get: git, trigger: false, passed: [spec-tests] }
        - { get: git-ci, trigger: false }
        - get: bosh-release-postgres
          trigger: true
          params:
            tarball: false
      - task: update-bosh-release
        file: git-ci/ci/tasks/update-bosh-release/task.yml
        input_mapping:
          bosh-release: bosh-release-postgres
        params:
          OPS_FILE_PATH: manifests/releases/postgres.yml
          RELEASE_NAME: postgres
          BRANCH: (( grab meta.github.branch ))
      - put: git
        params:
          merge: true
          repository: pushme

- name: prometheus-release
  public: true
  serial: true
  serial_groups: [bosh-release]
  plan:
    - do:
      - in_parallel:
        - { get: git, trigger: false, passed: [spec-tests] }
        - { get: git-ci, trigger: false }
        - get: bosh-release-prometheus
          trigger: true
          params:
            tarball: false
      - task: update-bosh-release
        file: git-ci/ci/tasks/update-bosh-release/task.yml
        input_mapping:
          bosh-release: bosh-release-prometheus
        params:
          OPS_FILE_PATH: manifests/releases/prometheus.yml
          RELEASE_NAME: prometheus
          BRANCH: (( grab meta.github.branch ))
      - put: git
        params:
          merge: true
          repository: pushme